Install more prerequisites in GitHub Actions.

diff --git a/.github/workflows/run-flake8-pylint-via-pytest.yml b/.github/workflows/run-flake8-pylint-via-pytest.yml
--- a/.github/workflows/run-flake8-pylint-via-pytest.yml
+++ b/.github/workflows/run-flake8-pylint-via-pytest.yml
@@ -77,9 +77,28 @@ jobs:
       run: |
         pytest --flake8 --mypy --pylint -m "flake8 or mypy or pylint or not slow"
 
-    - name: Print Mercurial version, do not upgrade for now as 5.3.1 seems recent enough
+    - name: Check versions
       run: |
+        gcc --version  || true  # May not be installed
+        g++ --version  || true  # May not be installed
+        clang --version
+        clang++ --version
         hg --version
+        llvm-symbolizer --version || true  # Ignore exit code if llvm-symbolizer does not exist
+        which llvm-config || true  # Find out location of llvm-config
+        export LLVM_CONFIG=/usr/local/clang-9.0.1/bin/llvm-config  # From llvm-config location
+        llvm-config --version || true  # Ignore exit code if llvm-config does not exist
+        /usr/bin/llvm-config --version || true  # Ignore exit code if llvm-config does not exist
+        npm --version  || true  # May not be installed
+    - name: Install latest version of Rust via rustup
+      run: |
+        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
+        source $HOME/.cargo/env
+        rustup update stable
+        which rustup
+        rustup --version
+        which rustc
+        rustc --version
     - name: Set project cache folder environment variable
       run: |
         echo ::set-env name=MC_HG_REPO_PATH::$HOME/.cache/${{ github.event.repository.name }}
@@ -91,6 +110,7 @@ jobs:
         date
         time hg clone --stream https://hg.mozilla.org/mozilla-central/ $MC_HG_REPO_PATH/mozilla-central/
         date
+    # prerequisite and m-c verification should be a fast compile test, and actual compilation a slow compile test
     # Commented out as there are currently no slow tests
     # - name: Run only slow tests, using pytest
     #   run: |
